# Generated by Django 5.1.3 on 2024-12-06 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=11, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca1', models.IntegerField()),
                ('ca2', models.IntegerField()),
                ('exam', models.IntegerField()),
                ('generated', models.BooleanField(default=False)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.level')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.term')),
            ],
            options={
                'unique_together': {('student', 'subject', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('overall_total', models.IntegerField(blank=True, null=True)),
                ('next_term_begin', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('pin', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_results', to='profiles.level')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='profiles.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='profiles.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports', to='profiles.term')),
                ('subjects', models.ManyToManyField(related_name='subjects', to='report_card.subjectentry')),
            ],
            options={
                'unique_together': {('session', 'term', 'student', 'level')},
            },
        ),
    ]
